FROM alpine

CMD ["echo","Rodei na execução"]
git clone https://github.com/profjoaomenk/Docker-NodeJs-HelloWorld.git​

cd Docker-NodeJs-HelloWorld

#​docker build -t nodehelloworld .

#​docker container run -d -p 3030:3030 --name apphello nodehelloworld​

#docker build -t testecmd .

#docker container run --rm testecmd