FROM ubuntu

EXPOSE 80/tcp
EXPOSE 80/udp

#docker image build -t expose .
#docker container run --name antonio-teste-expose -it antonio-expose /bin/bash
#docker image inspect --format='' expose |grep ExposedPor

