version: '2'

volumes: 
    dados:

networks:
  banco:
  web:
  fila:

services:    
    db:
      image: postgres:9.6
      volumes:
         # Volume dos dados
        - dados:/var/lib/postgresql/data
        # Scripts
        - ./scripts:/scripts
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

        # Passa variáveis de Ambiente para o Container
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres

      networks: 
        - banco

    frontend:
      image: nginx:1.13
      volumes:
        # Site
        - ./web:/usr/share/nginx/html/
        # Configuração do proxy reverso
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
      networks:
          - web
      depends_on:
          - app
    app:
      image: python:3.6
      environment:
          - DB_NAME=email_sender
      volumes:
      # Aplicação
          - ./app:/app
      working_dir: /app
      command: bash ./app.sh
      ports:
          - 8080:8080
      networks:
        - banco
        - web
        - fila
      depends_on:
        - db
        - queue
    worker:
      build: worker
      volumes:
      # Worker
      - ./worker:/worker
      working_dir: /worker
      command: worker.py
      networks:
        - fila
      depends_on:
        - queue
        - app
    queue:
      image: redis:3.2
      networks:
        - fila


     





