# From base image node
FROM node:16

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copying all the files from your file system to container file system
COPY package.json .

# Install all dependencies
RUN npm install

# Copy other files too
COPY ./ .

# Adicionando a variável de ambiente
ENV REACT_APP_AZURE_COMPUTER_VISION_KEY="bca45af71cea48d2aa268a19e36cee45"
ENV REACT_APP_AZURE_COMPUTER_VISION_ENDPOINT="https://know-image-pf1776.cognitiveservices.azure.com/"​

# Expose the port
EXPOSE 9000

# Command to run app when intantiate an image
CMD ["npm","start"]

#docker build -t iot-CognitiveServices .

#docker container run -d -p 9000:9000 --name REACT_APP_AZURE_COMPUTER_VISION iot-cognitiveservices