FROM ubuntu

RUN apt-get update && apt-get -y upgrade && apt-get install openjdk-8-jdk --yes 
ADD Dockerfile /root/arquivo-host-transferido.txt

#docker image build -t add-copy .
#docker container run --name testeadd -it add-copy /bin/bash
