FROM openjdk:8u111-alpine


RUN apt-get update && apt-get -y upgrade && apt-get install openjdk-8-jdk --yes 
ADD Dockerfile /root/arquivo-host-transferido.txt

#docker image build -t antoniofigueiredo-add-copy .
#docker container run --name antoniofigueiredo -it antoniofigueiredo-add-copy /bin/bash
