FROM 123lin/ubuntu_python
RUN apt-get update && apt-get -y upgrade && apt-get install python3 --yes && apt-get install curl --yes
RUN touch arquivo-de-boas-vindas.txt
RUN touch arquivo-de-boas-vindas2.txt

#docker container run -it ubuntu_python /bin/bash
